//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourthCoffee.DataService.Infrastructure
{
    using System.Runtime.Serialization;
    using System.Diagnostics;


    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="SalesPerson", Namespace="http://schemas.datacontract.org/2004/07/FourthCoffee.DataService.Infrastructure")]

    public partial class SalesPerson : object, IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AreaField;
        
        private string EmailAddressField;
        
        private string FirstNameField;
        
        private string SurnameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area
        {
            get
            {
                return this.AreaField;
            }
            set
            {
                this.AreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISalesService")]
public interface ISalesService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetSalesPerson", ReplyAction="http://tempuri.org/ISalesService/GetSalesPersonResponse")]
    FourthCoffee.DataService.Infrastructure.SalesPerson GetSalesPerson(string emailAddress);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetSalesPerson", ReplyAction="http://tempuri.org/ISalesService/GetSalesPersonResponse")]
    System.Threading.Tasks.Task<FourthCoffee.DataService.Infrastructure.SalesPerson> GetSalesPersonAsync(string emailAddress);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISalesServiceChannel : ISalesService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SalesServiceClient : System.ServiceModel.ClientBase<ISalesService>, ISalesService
{
    
    public SalesServiceClient()
    {
    }
    
    public SalesServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SalesServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SalesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SalesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public FourthCoffee.DataService.Infrastructure.SalesPerson GetSalesPerson(string emailAddress)
    {
        return base.Channel.GetSalesPerson(emailAddress);
    }
    
    public System.Threading.Tasks.Task<FourthCoffee.DataService.Infrastructure.SalesPerson> GetSalesPersonAsync(string emailAddress)
    {
        return base.Channel.GetSalesPersonAsync(emailAddress);
    }
}
